@startgantt
'18th - 19th October
[map and character design] lasts 2 days and is colored in Lavender/Blue
'22nd - 5th November October
[IMPLEMENTATION PHASE] lasts 14 days and starts 2 days after [map and character design]'s end
[Playtesting] lasts 13 days and starts 1 days after [IMPLEMENTATION PHASE]'s start 

@endgantt