package io.github.some_example_name;

/**
 * NEW
 *
 * Represents the achievements that the player can achieve
 * Each achievement provides a positive or negative
 */
public class Achievement {
    /** The display name of the achievement. */
    public String name;
    /** A description on how the achievement was earned. */
    public String description;
    /** The score bonus or subtraction generated by the achievement. */
    public int bonusScore;

    /**
     * Creates a new achievement with a name, description, and score bonus.
     *
     * @param name the display name of the achievement
     * @param description a short explanation of the achievement
     * @param bonusScore the score bonus or subtraction generated when earned
     */
    public Achievement(String name, String description, int bonusScore) {
        this.name = name;
        this.description = description;
        this.bonusScore = bonusScore;
    }
}
